import React from 'react';
import { X, FileText, Activity, Calendar, MapPin, TrendingUp, Zap, BrainCircuit } from 'lucide-react';

const generateInsight = (disease, location) => {
    if (!disease) return "Analyzing data patterns...";

    const d = disease.toLowerCase();

    if (d.includes('cholera')) {
        return `CareSignal detected a sudden spike in water-borne pathogens in ${location}. Analysis correlates this with recent rainfall and water stagnation reports. Recommended Action: Testing of local water supply.`;
    }
    if (d.includes('dengue')) {
        return `Vector density analysis indicates a 40% increase in mosquito breeding grounds in ${location}. Correlates with humidity levels.`;
    }
    if (d.includes('fever') || d.includes('viral')) {
        return `Community transmission rates have crossed the threshold (R0 > 1.5). Likely seasonal flu variant.`;
    }

    // Default
    return `Anomaly detection algorithms flagged a statistical deviation of ${Math.floor(Math.random() * 20) + 15}% from the 14-day moving average.`;
};

const generateActions = (disease, location) => {
    if (!disease) return [];
    const d = disease.toLowerCase();

    // Water-borne: Cholera, Typhoid, Diarrhea
    if (d.includes('cholera') || d.includes('typhoid') || d.includes('diarrhea')) {
        return [
            `Immediate bacteriological testing of local water sources (taps/wells).`,
            `Distribute Chlorine tablets (Halogen) to households in the affected cluster.`,
            `Inspect sewage pipelines for cross-contamination leaks.`
        ];
    }

    // Vector-borne: Dengue, Malaria, Chikungunya
    if (d.includes('dengue') || d.includes('malaria') || d.includes('chikungunya')) {
        return [
            `Initiate thermal fogging and indoor residual spraying (IRS) within 400m radius.`,
            `Conduct door-to-door larval survey to identify breeding spots.`,
            `Alert local fever clinics to prepare platelet transfusion kits.`
        ];
    }

    // Air-borne: Respiratory Issue, Flu, Viral
    if (d.includes('respiratory') || d.includes('flu') || d.includes('viral')) {
        return [
            `Analyze local AQI (Air Quality Index) and PM2.5 levels for correlation.`,
            `Issue advisory for N95 mask usage in high-density public areas.`,
            `Setup localized fever screening camps at ward entry points.`
        ];
    }

    // Contagious: Measles, Rash
    if (d.includes('measles') || d.includes('rash')) {
        return [
            `Immediate isolation of index cases to prevent community transmission.`,
            `Audit vaccination records (MMR) for children under 5 in the zone.`,
            `Track contact history for the last 7 days.`
        ];
    }

    // Default
    return [
        `Increase active surveillance frequency to hourly intervals.`,
        `Review stock of essential medicines at the nearest PHC.`,
        `Isolate confirmed cases and monitor close contacts.`
    ];
};

export default function InsightModal({ isOpen, onClose, signal }) {
    if (!isOpen || !signal) return null;

    const locationName = signal.zone?.name || `Zone ${signal.zone_id}`;
    const insightText = generateInsight(signal.syndrome, locationName);
    const actions = generateActions(signal.syndrome, locationName);

    return (
        <div className="fixed inset-0 z-[1000] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm animate-in fade-in duration-200">
            <div
                className="bg-white rounded-xl shadow-2xl w-full max-w-2xl overflow-hidden border border-slate-200 flex flex-col max-h-[90vh]"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Header */}
                <div className="bg-slate-50 border-b border-slate-200 px-6 py-4 flex justify-between items-center shrink-0">
                    <div className="flex items-center space-x-3">
                        <div className="bg-indigo-100 p-2 rounded-lg text-indigo-600">
                            <BrainCircuit size={24} />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-slate-800">AI Diagnostic Report</h2>
                            <p className="text-xs text-slate-500 font-mono uppercase tracking-wider">Generated by CareSignal Engine</p>
                        </div>
                    </div>
                    <button
                        onClick={onClose}
                        className="p-2 hover:bg-slate-200 rounded-full text-slate-400 hover:text-slate-600 transition-colors"
                    >
                        <X size={20} />
                    </button>
                </div>

                {/* Content */}
                <div className="p-8 overflow-y-auto">

                    {/* Metabolic Panel Style Header */}
                    <div className="grid grid-cols-2 gap-6 mb-8 border-b border-slate-100 pb-6">
                        <div>
                            <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">Target Anomaly</label>
                            <div className="text-xl font-bold text-slate-900 flex items-center">
                                <Activity className="w-5 h-5 mr-2 text-indigo-500" />
                                {signal.syndrome} Spike
                            </div>
                        </div>
                        <div>
                            <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">Location Context</label>
                            <div className="text-xl font-bold text-slate-900 flex items-center">
                                <MapPin className="w-5 h-5 mr-2 text-slate-400" />
                                {locationName}
                            </div>
                        </div>
                        <div>
                            <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">Detection Time</label>
                            <div className="text-sm font-medium text-slate-700 flex items-center">
                                <Calendar className="w-4 h-4 mr-2 text-slate-400" />
                                {new Date(signal.date).toLocaleString()}
                            </div>
                        </div>
                        <div>
                            <label className="text-xs font-bold text-slate-400 uppercase tracking-wider block mb-1">Confidence Score</label>
                            <div className="text-sm font-bold text-emerald-600 flex items-center">
                                98.4% (High Confidence)
                            </div>
                        </div>
                    </div>

                    {/* AI Insight Box - Darker Theme */}
                    <div className="bg-indigo-600 rounded-xl p-6 border border-indigo-700 shadow-inner mb-8 text-white">
                        <h3 className="text-xs font-bold text-indigo-200 uppercase tracking-wider mb-3 flex items-center">
                            <BrainCircuit className="w-4 h-4 mr-2" />
                            Use Case Explanation
                        </h3>
                        <p className="text-lg leading-relaxed font-medium text-white">
                            "{insightText}"
                        </p>
                    </div>

                    {/* Metrics Badges (Replacing Progress Bars) */}
                    <div className="mb-8 grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 flex items-center space-x-3">
                            <div className="bg-red-100 p-2 rounded-full text-red-600">
                                <TrendingUp size={18} />
                            </div>
                            <div>
                                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Trend Analysis</label>
                                <div className="font-bold text-slate-800 text-sm">
                                    📈 +31% vs Average <span className="text-red-600 text-xs ml-1">(Critical)</span>
                                </div>
                            </div>
                        </div>
                        <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 flex items-center space-x-3">
                            <div className="bg-amber-100 p-2 rounded-full text-amber-600">
                                <Zap size={18} />
                            </div>
                            <div>
                                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Spread Speed</label>
                                <div className="font-bold text-slate-800 text-sm">
                                    ⚡ Rapid Expansion
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Recommended Response Protocol */}
                    <div>
                        <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 border-b border-slate-100 pb-2">Recommended Response Protocol</h3>
                        <ul className="space-y-3">
                            {actions.map((action, i) => (
                                <li key={i} className="flex items-start">
                                    <div className="flex-shrink-0 w-6 h-6 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center text-xs font-bold mr-3 mt-0.5 border border-indigo-100">
                                        {i + 1}
                                    </div>
                                    <span className="text-slate-700 font-medium text-sm">{action}</span>
                                </li>
                            ))}
                        </ul>
                    </div>

                </div>

                {/* Footer Actions */}
                <div className="bg-slate-50 border-t border-slate-200 px-6 py-4 flex justify-end space-x-3 shrink-0">
                    <button
                        onClick={onClose}
                        className="px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-200 rounded-lg transition-colors"
                    >
                        Dismiss
                    </button>
                    <button
                        className="px-4 py-2 text-sm font-bold text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg shadow-md flex items-center transition-colors"
                        onClick={(e) => {
                            e.target.innerText = "Downloading...";
                            setTimeout(() => {
                                e.target.innerText = "Report Downloaded";
                                setTimeout(() => onClose(), 1000);
                            }, 1500);
                        }}
                    >
                        <FileText className="w-4 h-4 mr-2" />
                        Generate PDF Report
                    </button>
                </div>
            </div>
        </div>
    );
}
